name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "main"

env:
  PROJECT_NAME: git-ai

jobs:
  format:
    name: 📝 Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: cargo install cargo-xfmt
      - run: cargo xfmt --check

  lint:
    name: 🤓 Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: cargo clippy --all-targets --workspace -- -D warnings

  build:
    strategy:
      matrix:
        config:
          - name: 🐥 Linux AMD64
            runner: ubuntu-24.04
            os: linux
            arch: amd64
            target: x86_64-unknown-linux-musl
            run: |
              sudo apt-get update
              sudo apt-get install -y musl-tools
              rustup target add x86_64-unknown-linux-musl

          - name: 🐥 Linux ARM64
            runner: ubuntu-24.04-arm
            os: linux
            arch: arm64
            target: aarch64-unknown-linux-musl
            run: |
              sudo apt-get update
              sudo apt-get install -y musl-tools
              rustup target add aarch64-unknown-linux-musl

          - name: 🍎 MacOS ARM64
            runner: macos-15
            os: macos
            arch: arm64
            target: aarch64-apple-darwin

          # - name: 🟦 Windows AMD64
          #   runner: windows-latest
          #   os: windows
          #   arch: amd64
          #   target: x86_64-pc-windows-msvc

          # - name: 🟦 Windows ARM64
          #   runner: windows-latest
          #   os: windows
          #   arch: arm64
          #   target: aarch64-pc-windows-msvc
          #   run: rustup target add aarch64-pc-windows-msvc


    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - if: matrix.config.run
        run: ${{ matrix.config.run }}
      - env:
          os: "${{ matrix.config.os }}"
          arch: "${{ matrix.config.arch }}"
          profile: "release"
        run: cargo build --target ${{ matrix.config.target }} --release

      - run: mkdir -p artifacts/${{ matrix.config.os }}-${{ matrix.config.arch }}
      - env:
          EXE: ${{ runner.os == 'Windows' && '.exe' || '' }}
        run: cp target/${{ matrix.config.target }}/release/git-ai$EXE ./artifacts/${{ matrix.config.os }}-${{ matrix.config.arch }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.config.os }}-${{ matrix.config.arch }}
          path: ${{ github.workspace }}/artifacts/**/*
          if-no-files-found: error
          retention-days: 1

  publish_github_release:
    name: "🔄 Publish Github Release"
    runs-on: ubuntu-24.04
    outputs:
      VERSION: ${{ steps.tag.outputs.VERSION }}
    needs:
      - format
      - lint
      - build
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with: { path: artifacts }
      - name: Publish` Github Release
        env:
          GH_TAG: ${{needs.vars.outputs.GH_TAG}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          LAST_TAG=$(curl -sSL https://api.github.com/repos/alshdavid/${{ env.PROJECT_NAME }}/releases/latest | jq -r ".tag_name" | cut -d "." -f 3)
          if [ "$LAST_TAG" = "" ]; then
            LAST_TAG="0"
          fi
          declare -i var="$LAST_TAG"
          var=$var+1
          TAG="0.0.$var"

          echo "Tag: ${TAG}"

          gh release create $TAG  --draft --notes "Automatically built binaries"
          gh release edit $TAG --title "🚀 Latest"

          cd artifacts

          for name in *; do
            echo $name
            cd $name
            chmod +x ./*

            tar -czf ./$name.tar.gz ./*
            gh release upload $TAG ${name}.tar.gz
            rm -rf ./*.tar.gz

            tar -cJf ./$name.tar.xz ./*
            gh release upload $TAG ${name}.tar.xz
            rm -rf ./*.tar.xz

            zip ./$name.zip ./*
            gh release upload $TAG ${name}.zip
            rm -rf ./*.zip

            cd ..
          done

          gh release edit $TAG --draft=false
